"""empty message

Revision ID: e265c5f4595d
Revises: c45a217aea16
Create Date: 2023-01-23 15:52:36.505511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e265c5f4595d'
down_revision = 'c45a217aea16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('episode_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['episode_id'], ['episode.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('favorites')
    op.drop_table('characters__locations')
    op.drop_table('episodes__characters')
    op.drop_table('locations__episodes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations__episodes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('episode_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['episode.id'], name='locations__episodes_episode_id_fkey'),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name='locations__episodes_location_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='locations__episodes_pkey')
    )
    op.create_table('episodes__characters',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('episode_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name='episodes__characters_character_id_fkey'),
    sa.ForeignKeyConstraint(['episode_id'], ['episode.id'], name='episodes__characters_episode_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='episodes__characters_pkey')
    )
    op.create_table('characters__locations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name='characters__locations_character_id_fkey'),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name='characters__locations_location_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='characters__locations_pkey')
    )
    op.create_table('favorites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('episode_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name='favorites_character_id_fkey'),
    sa.ForeignKeyConstraint(['episode_id'], ['episode.id'], name='favorites_episode_id_fkey'),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name='favorites_location_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorites_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorites_pkey')
    )
    op.drop_table('favorite')
    # ### end Alembic commands ###
